version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
